version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: vettrack_db
    restart: unless-stopped
    env_file:
      - .env.local
    ports:
      - "5433:5432"
    volumes:
      - clinica_vet_data:/var/lib/postgresql/data
      - ./backend:/scripts

  redis:
    image: redis:7-alpine
    container_name: clinica_vet_redis
    restart: unless-stopped
    ports:
      - "6379:6379"

volumes:
  clinica_vet_data: